kind: DaemonSet
apiVersion: apps/v1
metadata:
    labels:
        app: loki-canary
    name: loki-canary
spec:
    selector:
        matchLabels:
            app: loki-canary
    template:
        metadata:
            name: loki-canary
            labels:
                app: loki-canary
        spec:
            containers:
                - name: loki-canary
                  env:
                      - name: MY_POD_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                  args:
                      - -addr=loki:3100
                      - -labelname=instance
                      - -labelvalue=$(MY_POD_NAME)
                  image: grafana/loki-canary:1.5.0
                  imagePullPolicy: IfNotPresent
                  resources: {}
                  ports:
                      - containerPort: 3500
                        name: http-metrics
