apiVersion: v1
kind: Service
metadata:
    name: loki-canary
    labels:
        app: loki-canary
spec:
    type: ClusterIP
    selector:
        app: loki-canary
    ports:
        - name: metrics
          protocol: TCP
          port: 3500
          targetPort: 3500
