# Source: loki/templates/service-headless.yaml
apiVersion: v1
kind: Service
metadata:
    name: promtail
    namespace: loki
    labels:
        app: promtail
        monitoring: loki
        chart: loki-0.25.1
        release: loki
        heritage: Helm
spec:
    clusterIP: None
    ports:
        - port: 3101
          protocol: TCP
          name: http-metrics
          targetPort: http-metrics
    selector:
        app: promtail
