# Source: promtail/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: promtail
    namespace: loki
    labels:
        app: promtail
        chart: promtail-0.19.1
        heritage: Helm
        release: promtail
rules:
    - apiGroups: ["extensions"]
      resources: ["podsecuritypolicies"]
      verbs: ["use"]
      resourceNames: [promtail]
