apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: loki
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 20Gi
    storageClassName: do-block-storage-safe
