apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: loki
spec:
    endpoints:
        - port: http-metrics
    namespaceSelector: {}
    selector:
        matchLabels:
            name: loki
