apiVersion: v1
kind: Service
metadata:
    name: influxdb
    namespace: influxdb
spec:
    ports:
        - name: influxdb
          port: 8086
          targetPort: 8086
    type: ClusterIP
    clusterIP: None
