namespace: www
commonLabels:
    app: www.jrock.us
resources:
    - namespace.yaml
    - registry-creds.yaml
    - deployment.yaml
    - service.yaml
    - poddisruptionbudget.yaml
configMapGenerator:
    - name: www-jrock-us-nginx-config
      files:
          - nginx.conf
          - zipkin-nginx-config.json
images:
    - name: www
      newName: registry.jrock.us/www
      newTag: 0.0.66
