namespace: www
commonLabels:
    app: www.jrock.us
resources:
    - namespace.yaml
    - deployment.yaml
    - service.yaml
    - poddisruptionbudget.yaml
configMapGenerator:
    - name: www-jrock-us-nginx-config
      files:
          - nginx.conf
          - zipkin-nginx-config.json
images:
    - name: www
      newName: registry.digitalocean.com/jrockus/www
      newTag: f2e5f53a19de969c9ad75a0de221e71a2c1d6236
