apiVersion: apps/v1
kind: DaemonSet
metadata:
    generation: 1
    labels:
        app: do-node-agent
    name: do-node-agent
    namespace: kube-system
spec:
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: do-node-agent
    template:
        metadata:
            annotations:
                clusterlint.digitalocean.com/disabled-checks: hostpath-volume
            creationTimestamp: null
            labels:
                app: do-node-agent
        spec:
            containers:
                - args:
                      - --path.procfs=/host/proc
                      - --path.sysfs=/host/sys
                      - --k8s-metrics-path=http://kube-state-metrics.monitoring.svc.cluster.local:8081/metrics
                      - --additional-label=kubernetes_cluster_uuid:d026c70b-9e84-4ee6-8ad7-2f9d01c258c2
                  command:
                      - /bin/do-agent
                  image: docker.io/digitalocean/do-agent:3
                  imagePullPolicy: IfNotPresent
                  name: do-node-agent
                  resources:
                      limits:
                          cpu: 102m
                          memory: 100Mi
                      requests:
                          cpu: 102m
                          memory: 80Mi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                      - mountPath: /host/proc
                        name: proc
                        readOnly: true
                      - mountPath: /host/sys
                        name: sys
                        readOnly: true
                      - mountPath: /host/root
                        mountPropagation: HostToContainer
                        name: root
                        readOnly: true
            dnsPolicy: ClusterFirstWithHostNet
            hostNetwork: true
            nodeSelector:
                beta.kubernetes.io/os: linux
            priorityClassName: system-node-critical
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext:
                runAsNonRoot: true
                runAsUser: 65534
            serviceAccount: do-agent
            serviceAccountName: do-agent
            terminationGracePeriodSeconds: 30
            tolerations:
                - operator: Exists
            volumes:
                - hostPath:
                      path: /proc
                      type: ""
                  name: proc
                - hostPath:
                      path: /sys
                      type: ""
                  name: sys
                - hostPath:
                      path: /
                      type: ""
                  name: root
    updateStrategy:
        rollingUpdate:
            maxUnavailable: 1
        type: RollingUpdate
