namespace: kube-system
resources:
    - cluster-role.yaml
    - cluster-role-binding.yaml
    - service-account.yaml
    - deployment.yaml
    - service.yaml
    - servicemonitor.yaml
images:
    - name: kube-state-metrics
      newName: quay.io/coreos/kube-state-metrics
      newTag: v1.9.7
