apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: kube-state-metrics
    namespace: kube-system
spec:
    endpoints:
        - port: http-metrics
    selector:
        matchLabels:
            app.kubernetes.io/name: kube-state-metrics
