namespace: prometheus
resources:
    - tailscale.yaml
    - tailscale.sealed-secret.json
configMapGenerator:
    - name: prom-rules
      files:
          - prometheus.yml
          - legacy.yml
      options:
          disableNameSuffixHash: true
    - name: alert-rules
      files:
          - monitoring-kube-state-metrics-alerts.yml
          - monitoring-self-check-alerts.yml
          - postgres-postgres-alerts.yml
      options:
          disableNameSuffixHash: true
