scrape_configs:
    - job_name: tailnet
      proxy_url: http://localhost:1055/
      static_configs:
          - targets:
                - keqing:9100
                - vm:9100
                - octopi:9100
                - orangepi5max:9100
    - job_name: "kubernetes-apiservers-fixed"
      kubernetes_sd_configs:
          - role: endpoints
      scheme: https
      tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
          - source_labels:
                [
                    __meta_kubernetes_namespace,
                    __meta_kubernetes_service_name,
                    __meta_kubernetes_endpoint_port_name,
                ]
            action: keep
            regex: default;kubernetes;https
