# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: tailscale
rules:
    - apiGroups: [""] # "" indicates the core API group
      resources: ["secrets"]
      # Create can not be restricted to a resource name.
      verbs: ["create"]
    - apiGroups: [""] # "" indicates the core API group
      resourceNames: ["tailscale-auth", "tailscale-prometheus", "tailscale-prometheus-pushgateway"]
      resources: ["secrets"]
      verbs: ["get", "update", "patch"]
    - apiGroups: [""] # "" indicates the core API group
      resources: ["events"]
      verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: tailscale-prometheus-server
subjects:
    - kind: ServiceAccount
      name: "prometheus-server"
roleRef:
    kind: Role
    name: tailscale
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: tailscale-prometheus-pushgateway
subjects:
    - kind: ServiceAccount
      name: "prometheus-prometheus-pushgateway"
roleRef:
    kind: Role
    name: tailscale
    apiGroup: rbac.authorization.k8s.io
