namespace: www
commonLabels:
    app: www.jrock.us
resources:
    - namespace.yaml
    - deployment.yaml
    - service.yaml
secretGenerator:
    - name: registry-credentials
      files:
          - ".dockerconfigjson=docker.secret.json"
      type: kubernetes.io/dockerconfigjson
images:
    - name: www
      newName: docker.pkg.github.com/jrockway/jrock.us/www
      newTag: 047aa4adc5bfe222eadb561b4758a43c5a8f63ca
