apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: jrock-us
spec:
    secretName: jrock-us-tls
    issuerRef:
        name: letsencrypt-issuer
        kind: Issuer
    commonName: "*.jrock.us"
    dnsNames:
        - "*.jrock.us"
        - jrock.us
