apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  creationTimestamp: null
  name: jrock-us
spec:
  commonName: '*.jrock.us'
  dnsNames:
  - '*.jrock.us'
  - jrock.us
  issuerRef:
    kind: Issuer
    name: letsencrypt-issuer
  secretName: jrock-us-tls
status: {}
