apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ekglue
  namespace: concourse
spec:
  encryptedData:
    codecov: AgBUYJB+NKDLxwkEffD4kXBVZQhoo33cwrBpFEWhTpMPenDS9PIVZXLRr7547zT9xQNORTZNxU3Oebh40kP8/DK1JsK2OS6kUBOheSMAH4+TJPxPwnIbakdw83fTrIkJ2x9teGfDph2QSF8GI3Z8+B1UxgNq68S0837vgtzpW1LqihVzM4Lsh+TBaoiHUYfQ6p9dDjGoouhj3ZDj45N9uwdjkIFo80AISXaYE0uJfcLNWzBV9sGFNUbpKCYayBQBdT7GtkrcPuS6h4aDyiPR1gxBvOhNeN2Yl7bI0o7MiEyk5dn3I+M5WrIC+XUxa+c3AdIKfyPt0R8wqBq8cEACbKUxznNT84iWaH2TeDVnOkWk4mJuDPYPw1EWnl3UsWSkzyRIuArozfaytXBcRC6LeEAdWzTMtwDPfMPeRl40q+Royzgo4FD4cN+BP44YK4d3XiXoxFgv+xRf0+ctYRMGoJ4Cj1V9g85Nz9gPXP//Zirgo5zkBgKEE2eyWEC7gY4NGLwlZVB7MYlnw0I0Egz+U2tuEAye7qAFiWSguviv3NrEUQ/cKlFvb1T97ZSbzaJNq1oX5oXmJdZ14NzsMACEhahAHkMQegXIfqpZe/00VIjSEUQeHOh5UbhDNvbi/L6z/Tz23Vq/oSPTw+ZgwkZUwHwVgZJEzjagmrd6V/0tgCSiDwbBAzi8a5sl5RsnOxh9W4zAo7UqhtFatuFbfo9gRizF1C52m+sjycDkCnDLdiT9v+MI5RU=
  template:
    metadata:
      creationTimestamp: null
      name: ekglue
      namespace: concourse
status: {}

