namespace: concourse-main
resources:
    - namespace.yaml
    - dockerhub-secret.yaml
secretGenerator:
    - name: registry
      literals:
          - "username=jrockway"
      files:
          - "password=docker-password.secret.txt"
    - name: versions
      files:
          - "secret_access_key=versions.secret.txt"
      literals:
          - "access_key_id=C6T2AXGG5F2CRDGVAACA"
          - "bucket=jrockus-versions"
          - "region_name=nyc3"
          - "endpoint=https://nyc3.digitaloceanspaces.com"
    - name: webhook
      files:
          - "token=webhook-token.secret.txt"
    - name: opinionated-server
      files:
          - "token=opinionated-server-codecov.secret.txt"
generatorOptions:
    disableNameSuffixHash: true # because the exact name of the secret appears in CI configs
