apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
    name: main
    namespace: monitoring
    labels:
        prometheus: main
spec:
    version: v0.21.0
    externalUrl: "https://alertmanager.jrock.us/"
    retention: 720h
    storage:
        volumeClaimTemplate:
            metadata:
                name: alertmanager-main-db
            spec:
                accessModes:
                    - ReadWriteOnce
                volumeMode: Filesystem
                resources:
                    requests:
                        storage: 5Gi
                storageClassName: do-block-storage-safe
    securityContext:
        fsGroup: 489
        runAsUser: 489
    initContainers:
        - command:
              - chown
              - -R
              - 489:489
              - /alertmanager
          image: busybox:1.30
          imagePullPolicy: IfNotPresent
          name: init-chown-data
          resources: {}
          securityContext:
              runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
              - mountPath: /alertmanager
                name: alertmanager-main-db
                subPath: alertmanager-db
    resources:
        requests:
            cpu: 100m
            memory: 100Mi
        limits:
            memory: 100Mi
