global:
    resolve_timeout: 5m
route:
    group_by: ["job"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
        - match:
              alertname: AlwaysFiring
          receiver: "status"
          repeat_interval: 5s
          group_wait: 0s
        - receiver: "discord"
    receiver: "null"
receivers:
    - name: "null"
    - name: "discord"
      webhook_configs:
          - url: "http://alertmanager-discord.monitoring.svc.cluster.local.:8080/"
    - name: "status"
      webhook_configs:
          - url: "http://alertmanager-status.monitoring.svc.cluster.local.:8080/webhook"
