namespace: monitoring
secretGenerator:
    - name: alertmanager-main
      files:
          - alertmanager.yaml
    - name: prometheus-additional
      files:
          - additional-prom.yaml
generatorOptions:
    disableNameSuffixHash: true
resources:
    - bundle.yaml
    - prom-main-clusterrole.yaml
    - alertmanager-spec.yaml
    - prometheus.yaml
    - self-check.yaml
