secretGenerator:
    - name: alertmanager-main
      files:
          - alertmanager.yaml
generatorOptions:
    disableNameSuffixHash: true
resources:
    - bundle.yaml
    - prom-main-clusterrole.yaml
    - alertmanager-spec.yaml
    - prometheus.yaml
