apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
    name: main
    namespace: monitoring
    labels:
        prometheus: main
spec:
    replicas: 1
    version: v2.15.2
    externalUrl: "https://prom.jrock.us/"
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    scrapeInterval: 15s
    serviceAccountName: prometheus-operator
    resources:
        requests:
            memory: 500Mi
    alerting:
        alertmanagers:
            - namespace: monitoring
              name: alertmanager-main
              port: web
