apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
    name: main
    namespace: monitoring
    labels:
        prometheus: main
spec:
    replicas: 1
    version: v2.15.2
    externalUrl: "https://prom.jrock.us/"
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    scrapeInterval: 15s
    serviceAccountName: prometheus-operator
    retention: 30d
    retentionSize: 20GB
    storage:
        volumeClaimTemplate:
            metadata:
                name: prometheus
            spec:
                accessModes:
                    - ReadWriteOnce
                volumeMode: Filesystem
                resources:
                    requests:
                        storage: 20Gi
                storageClassName: do-block-storage-safe
    securityContext:
        fsGroup: 489
        runAsUser: 489
    initContainers:
        - command:
              - chown
              - -R
              - 489:489
              - /prometheus
          image: busybox:1.30
          imagePullPolicy: IfNotPresent
          name: init-chown-data
          resources: {}
          securityContext:
              runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
              - mountPath: /prometheus
                name: prometheus-main-db
                subPath: prometheus-db
    resources:
        requests:
            memory: 500Mi
    alerting:
        alertmanagers:
            - namespace: monitoring
              name: alertmanager-main
              port: web
    additionalScrapeConfigs:
        name: prometheus-additional
        key: additional-prom.yaml
