apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
    labels:
        role: alert-rules
    name: self-check-alerts
spec:
    groups:
        - name: Watchdog
          rules:
              - alert: AlwaysFiring
                expr: vector(1)
                for: 1s
                labels:
                    severity: none
                annotations:
                    summary: "AlwaysFiring"
                    description: |
                        This is an alert meant to ensure that the entire alerting pipeline is functional.
                        This alert is always firing, therefore it should always be firing in Alertmanager.
