namespace: argocd
resources:
    - namespace.yaml
    - application-crd.yaml
    - appproject-crd.yaml
    - rbac.yaml
    - argocd-gpg-keys-cm.yaml
    - config.yaml
    - dex-service.yaml
    - controller-metrics-service.yaml
    - redis-service.yaml
    - repo-service.yaml
    - server-metrics-service.yaml
    - server-service.yaml
    - controller-deployment.yaml
    - dex-deployment.yaml
    - redis-deployment.yaml
    - repo-deployment.yaml
    - server-deployment.yaml
    - application.yaml
    - servicemonitors.yaml
images:
    - name: argocd
      newName: argoproj/argocd
      newTag: v1.7.7
    - name: redis
      newName: redis
      newTag: 5.0.8
