namespace: argocd
resources:
    - namespace.yaml
    - crds.yaml
    - rbac.yaml
    - config.yaml
    - dex-service.yaml
    - controller-metrics-service.yaml
    - redis-service.yaml
    - repo-service.yaml
    - server-metrics-service.yaml
    - server-service.yaml
    - controller-deployment.yaml
    - dex-deployment.yaml
    - redis-deployment.yaml
    - repo-deployment.yaml
    - server-deployment.yaml
    - application.yaml
