subscriptions:
    - recipients:
          - webhook:discord
      condition: "true"
      templates: discord-basic
triggers:
    - name: on-sync-succeeded
      enabled: true
    - name: on-sync-failed
      enabled: true
    - name: on-sync-status-unknown
      enabled: true
    - name: on-sync-running
      enabled: true
    - name: on-health-degraded
      enabled: true
templates:
    - name: discord-basic
      webhook:
          discord:
              method: "POST"
              path: ""
              body: |
                  {"content":"{{ .app.metadata.name }} -> {{ .app.status.sync.status }}"}
