subscriptions:
    - recipients:
          - webhook:discord
      condition: "true"
      trigger: ping-discord
triggers:
    - name: on-sync-succeeded
      enabled: false
    - name: on-sync-failed
      enabled: false
    - name: on-sync-status-unknown
      enabled: false
    - name: on-sync-running
      enabled: false
    - name: on-health-degraded
      enabled: false
    - name: ping-discord
      enabled: true
      condition: "app.status.operationState.phase in ['Error', 'Failed', 'Succceeded']"
      template: discord-basic
templates:
    - name: discord-basic
      webhook:
          discord:
              method: "POST"
              path: ""
              body: |
                  {"content":"{{ .app.metadata.name }}: Phase {{ .app.status.operationState.phase }}\\n => {{ .app.status.sync.status }} "}
