subscriptions:
    - recipients:
          - webhook:discord
          - grafana:test
triggers:
    - name: on-sync-succeeded
      enabled: true
    - name: on-sync-failed
      enabled: true
    - name: on-sync-status-unknown
      enabled: true
    - name: on-sync-running
      enabled: true
    - name: on-health-degraded
      enabled: true
templates:
    - name: discord-message
      webhook:
          discord:
              method: POST
              body: |
                  {"content":"Application {{.app.metadata.name}} sync is {{.app.status.sync.status}}.  {{.context.argocdUrl}}/applications/{{.app.metadata.name}}"}
