apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
    name: prometheus-main
rules:
    - apiGroups: [""]
      resources:
          - nodes
          - services
          - endpoints
          - pods
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources:
          - configmaps
      verbs: ["get"]
    - nonResourceURLs: ["/metrics"]
      verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: prometheus-operator
        app.kubernetes.io/version: v0.35.1
    name: prometheus-main
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: prometheus-main
subjects:
    - kind: ServiceAccount
      name: prometheus-operator
      namespace: monitoring
