apiVersion: v1
kind: Service
metadata:
    name: redis
spec:
    selector:
        component: redis
    type: ClusterIP
    clusterIP: None
    ports:
        - name: redis
          port: 6379
          targetPort: 6379
