apiVersion: apps/v1
kind: Deployment
metadata:
    name: cert-manager-cainjector
spec:
    template:
        spec:
            containers:
                - name: cert-manager
                  resources:
                      requests:
                          cpu: 10m
                          memory: 128Mi
                      limits:
                          memory: 128Mi
