apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
    - cert-manager.yaml
patches:
    - path: cainjector-resources.yaml
    - path: manager-resources.yaml
    - path: webhook-resources.yaml
