apiVersion: apps/v1
kind: Deployment
metadata:
    name: cert-manager-webhook
    namespace: cert-manager
spec:
    template:
        spec:
            containers:
                - name: cert-manager-webhook
                  resources:
                      requests:
                          cpu: 10m
                          memory: 64Mi
                      limits:
                          memory: 64Mi
