apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  creationTimestamp: null
  name: master
spec:
  dnsNames:
  - master-0.master.postgres.svc.cluster.local
  - master.postgres.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
  secretName: master-tls
status: {}
