namespace: postgres
commonLabels:
    app: postgres-master
resources:
    - namespace.yaml
    - cert.yaml
    - service.yaml
    - pvc.yaml
    - statefulset.yaml
    - podmonitor.yaml
    - alerts.yaml
    - master-config-sealedsecret.yaml
images:
    - name: postgres
      newName: docker.io/postgres
      newTag: "17"
    - name: exporter
      newName: docker.io/wrouesnel/postgres_exporter
      newTag: v0.16.0
