apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: master-config
  namespace: postgres
spec:
  encryptedData:
    POSTGRES_INITDB_ARGS: AgA80Bf/wwwNq1ui5RSGPj7P6lafftKpvvT5/pxT4Sl7fVkxgGHgtQYJ2u14UUBGfFdDy46QyIcwXmg8b/kJ6BSFV83SU70wl2+G/imPDGh+OCgDkyxlvSKIjHjpbtqudxgujEBrkxtFsq1C6MOb1naBUwejGJNkQQH2JcBRJHtJE2ZO8Xa0ksoqqz5j9psw+j3m7N53DdLwW6umUNIEEGQiU09jN5Vb6Mg0oLEi2ySByHw3sslUSEENShCwop3RpYEHUTiLmRYI8lgX2ElSqvaWZjGsXMHO44jg3Kh3eQJr9wbeonDuv3/WvJ7LQzGC/l0nrmjjyOSwZY0RkG8Wkg0lHMInUwhlJH56j2mm+FBG9LXudh4o+P3KIOCK6gTRNSmG4L/Id78IsGj5wQY3LJjG0P4g1ZXgzajqwu/fZYe5e1POBITbQsdjNznyYWvjM9cfmRTxCRqHVgHVj8tpadRUy9xTZnogRLoXVc3ltwWjO5JIuqsdUrTmtZ/rMgIIBIfFWOz66NGdpqTu7ZR47oa0gIRaoSpOwfY9ygeEg1D6n5zQp9N/cDaHHIul0S6cJHaimNCWHkIhyYhgI9JBDDWpyYTEPsFwl3arzcUqw2y6n50xyYpDed3IYw5a/+q6dELxYQEKA+Jht5l1tsMy3yWoF0bBXV6Y4QdWeS86DAriyK3TIpEF3RI3Y9KfBxxvqW+3LyBrhywOo8K16HH3x49ON6Yju91OMUJb/fhKRzeZFOzWZUfFzW8LLZbhEQ==
    POSTGRES_PASSWORD: AgCvy6TyE4inC6RDMmNdm3H2vKdNOaW6dKNZZbL2ugFdKsjGwvJrR4w80q3SHSMkQPJitDSH2lT860GZl1zzwRKB7izeF2cS2CQ1ZIGnVoqbH7K8RohrzG3D4btmHsEIw015U6ONXdRxfQb5VUoowOBpZ/L+Ot9ibiukD08Y5GGXKQWHpsJ9stdn18qB4eI+DOhBQPFDkQv8SrHwuDHP0a/YrMLykdqCty6PKtyeNNhKeY6dTJ1yy4Tnb4eYI1PuhX0usrEDpbnF07eQwO1Jy5EItsYtjF3rXs+kcLeVUepKJZIA7ODJHXWlSWgaP+INuR4cuoT7+CQPgOfXp5EdSe48d97Zm9e42pg2JPcu4YgdyHBQE7x3Xai8ZiIAmvtCUE21T/Yu+bgsIx1FPTNb+S+S/9unSABxI7wARSumyM7GGY6JZNa926UY7m1f7Z8KySBvZsPcK3/fiMQiLNbNivG5ZKvB4BMwSQMX+O34Eg9EaeP3iEDN06CKYbZH2BVFSQfIM63eeY8t/pfPee5BE0q5zzkyeSZafJ16co8LTXnuseRZ475gusT90colQdUnL7xlC8iD/u7hrtmNG/qcRfuA8lp/3bx50/67lVFOh5k5Ylxhr4RImqPB8P8bCOq84uLfEyz8uVaWJ2mlBzg8cDe2d2XMDskSewTSObsqg93ncPKu5RliWpiyRO7SIhSXXirSSPrEDY2jAgFtBzFvVvRWuyV/yfjC5mxxG+y0IlrLV5HxNAhVaKZ4jbc=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres-master
      name: master-config
      namespace: postgres
    type: Opaque
status: {}

