apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: master
    namespace: monitoring
spec:
    selector:
        matchLabels:
            app: postgres-master
    podMetricsEndpoints:
        - port: http-metrics
