apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: master
    namespace: monitoring
spec:
    selector:
        matchLabels:
            app: postgres-master
    endpoints:
        - port: http-metrics
