apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: master-volume
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 20Gi
    storageClassName: do-block-storage
    # storageClassName: local-path
