apiVersion: v1
kind: Service
metadata:
    name: master
spec:
    clusterIP: None
    ports:
        - name: postgres
          port: 5432
          targetPort: 5432
        - name: http-metrics
          port: 9187
          targetPort: 9187
