apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: master
spec:
    replicas: 1
    serviceName: registry
    volumeClaimTemplates: []
    template:
        spec:
            containers:
                - name: postgres
                  image: postgres
                  envFrom:
                      - secretRef:
                            name: master-config
                  env:
                      - name: PGDATA
                        value: /var/lib/postgresql/data/pgdata
                  volumeMounts:
                      - name: data
                        mountPath: /var/lib/postgresql/data
                  readinessProbe:
                      tcpSocket:
                          port: 5432
                  livenessProbe:
                      tcpSocket:
                          port: 5432
                  ports:
                      - name: postgres
                        containerPort: 5432
                  # resources:
                  #     requests:
                  #         cpu: 300m
                  #         memory: "512Mi"
                  #     limits:
                  #         cpu: 300m
                  #         memory: "512Mi"
                - name: exporter
                  image: exporter
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 9187
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 9187
                  ports:
                      - name: http-metrics
                        containerPort: 9187
                  env:
                      - name: DATA_SOURCE_URI
                        value: "localhost:5432/?sslmode=disable"
                      - name: DATA_SOURCE_USER
                        value: "postgres"
                      - name: DATA_SOURCE_PASS
                        valueFrom:
                            secretKeyRef:
                                name: master-config
                                key: POSTGRES_PASSWORD
                      - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
                        value: "true"
            volumes:
                - name: data
                  persistentVolumeClaim:
                      claimName: master-volume
