apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: master
spec:
    replicas: 1
    serviceName: registry
    volumeClaimTemplates: []
    template:
        spec:
            securityContext:
                runAsUser: 999
                runAsGroup: 999
                fsGroup: 999
            containers:
                - name: postgres
                  image: postgres
                  envFrom:
                      - secretRef:
                            name: master-config
                  env:
                      - name: PGDATA
                        value: /var/lib/postgresql/data/pgdata
                  args:
                      - -c ssl=on
                      - -c ssl_cert_file=/tls/tls.crt
                      - -c ssl_key_file=/tls/tls.key
                  volumeMounts:
                      - name: data
                        mountPath: /var/lib/postgresql/data
                      - name: master-tls
                        mountPath: /tls
                  readinessProbe:
                      tcpSocket:
                          port: 5432
                  livenessProbe:
                      tcpSocket:
                          port: 5432
                  ports:
                      - name: postgres
                        containerPort: 5432
                  resources:
                      requests:
                          cpu: 500m
                          memory: 2Gi
                      limits:
                          memory: 2Gi
                - name: exporter
                  image: exporter
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 9187
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 9187
                  ports:
                      - name: http-metrics
                        containerPort: 9187
                  env:
                      - name: DATA_SOURCE_URI
                        value: "localhost:5432/?sslmode=disable"
                      - name: DATA_SOURCE_USER
                        value: "postgres"
                      - name: DATA_SOURCE_PASS
                        valueFrom:
                            secretKeyRef:
                                name: master-config
                                key: POSTGRES_PASSWORD
                      - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
                        value: "true"
                  resources:
                      requests:
                          cpu: 1m
                          memory: 32Mi
                      limits:
                          memory: 32Mi
            volumes:
                - name: data
                  persistentVolumeClaim:
                      claimName: master-volume-17
                - name: master-tls
                  secret:
                      secretName: master-tls
                      defaultMode: 416
