apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-password
  namespace: monitoring
spec:
  encryptedData:
    password: AgAf9s3FCyIQ0Uo97BzjqCtaOjp9SDkFI49x0X88Y3w/Cm590+DO8QN/DbMVq50YICbEdVUTNByFbpkkP3ttJHosrxOV+m9zvdVe9hxikO5DnF1uy9ippTRHTqk+JGfjkfH5WEgyWoYFg14pHC9IvcSsmaSLCB+mESve2WMc88rYR8I6xRMzhrDaZdpuMFbmV3zZZPes5EGgs2XhE1he6Vy2O68GJ9hxTaDOHgdZiS7YO2FLVTKS9AkdpM/KSKYZx/Es8z3u7vhyxvRcCr9z8niDWstvxSHhlx8g6LGwAVs+AAVLydEno+a8LJgF7cEXFRup9mYo/iR8nM4YuyXDNDAP0yRhlZd9+5z7fD9l9W3We6kyVzJvvxC9cK6kmHs2ZMuNx3ayEtumrsU9CjqPqsXi3429OUDrb+mVwX04SGgwd4FUHuCo7y/ERlxcxajxjDBhzsNOZD5v41Nwnqjr9gb5U3W5V5OgHQ27O2B1nf0nDv9CnSIwg7J8YR4UlGHAKtafE5Dxmch/d+pKQEfSW+fTZJTEHVZGzzKIhFdSVtCDPCOrVc3lXDhPnEEiLU0VIHR7Y5xxGoz83mJyHtpP5HDyCmH/JKLqnk/ElAXB8aA0pXS8mSAq+6RoncAcXnXHEhsuVsc4dHETKmcKhLDXNrzlUp9d+FcLCECLz70V9v1MTaJcFM0OhTWS4BrV6+ZtLj2vRMOamlZGaPB82T8=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-password
      namespace: monitoring
status: {}

