apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: grafana
spec:
    secretName: grafana-tls
    issuerRef:
        name: ca-issuer
        kind: ClusterIssuer
    commonName: "monitoring:grafana:https"
