apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  creationTimestamp: null
  name: grafana
spec:
  dnsNames:
  - grafana
  - grafana.monitoring
  - granana.monitoring.svc
  - granana.monitoring.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
  secretName: grafana-tls
status: {}
