apiVersion: apps/v1
kind: Deployment
metadata:
    name: grafana
    annotations:
        "sidecar.jaegertracing.io/inject": "jaeger"
spec:
    replicas: 1
    template:
        spec:
            containers:
                - name: grafana
                  image: grafana
                  env:
                      - name: GF_SECURITY_ADMIN_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: grafana-admin-password
                                key: password
                      - name: GF_DATABASE_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: grafana-database-password
                                key: password
                  ports:
                      - name: http
                        containerPort: 3000
                  resources:
                      requests:
                          memory: 200Mi
                  readinessProbe:
                      httpGet:
                          path: /api/health
                          port: http
                  volumeMounts:
                      - name: grafana-config
                        mountPath: /etc/grafana
            volumes:
                - name: grafana-config
                  configMap:
                      name: grafana-config
