apiVersion: apps/v1
kind: Deployment
metadata:
    name: grafana
    annotations:
        "sidecar.jaegertracing.io/inject": "jaeger"
spec:
    replicas: 1
    template:
        spec:
            containers:
                - name: grafana
                  image: grafana
                  env:
                      - name: GF_SECURITY_ADMIN_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: grafana-admin-password
                                key: password
                      - name: GF_DATABASE_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: grafana-database-password
                                key: password
                  ports:
                      - name: http
                        containerPort: 3000
                  resources:
                      requests:
                          memory: 512Mi
                          cpu: 50m
                      limits:
                          memory: 512Mi
                  readinessProbe:
                      httpGet:
                          path: /api/health
                          port: http
                          scheme: HTTPS
                          httpHeaders:
                              - name: Host
                                value: grafana.jrock.us
                  volumeMounts:
                      - name: grafana-config
                        mountPath: /etc/grafana
                      - name: grafana-tls
                        mountPath: /tls
            volumes:
                - name: grafana-config
                  configMap:
                      name: grafana-config
                - name: grafana-tls
                  secret:
                      secretName: grafana-tls
