apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogICAgcmVzb2x2ZV90aW1lb3V0OiAxMG0Kcm91dGU6CiAgICBncm91cF9ieTogWyJqb2IiXQogICAgZ3JvdXBfd2FpdDogMzBzCiAgICBncm91cF9pbnRlcnZhbDogNW0KICAgIHJlcGVhdF9pbnRlcnZhbDogMTJoCiAgICByZWNlaXZlcjogIm51bGwiCiAgICByb3V0ZXM6CiAgICAgICAgLSBtYXRjaDoKICAgICAgICAgICAgICBhbGVydG5hbWU6IFdhdGNoZG9nCiAgICAgICAgICByZWNlaXZlcjogIm51bGwiCnJlY2VpdmVyczoKICAgIC0gbmFtZTogIm51bGwiCg==
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
