apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: alertmanager-status
spec:
    selector:
        matchLabels:
            app: alertmanager-status
    podMetricsEndpoints:
        - port: debug
          path: /metrics
