apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook
  namespace: monitoring
spec:
  encryptedData:
    DISCORD_WEBHOOK: AgAh+B+TLXTerB5VBbuzTB9IKp0HsJsPUgaxpi0CFPJ07qftmPlsQrx34No/XNsGwUOzwYR3eTltMI5gc+T4Haqi9SpWzAPhfPZlXo3P8gxyXJNfIpXJV5E17+HuP77h/zMTjo9PKv1Sks/eqId2m/cnR4V+D78rxLuRQsJEshgKKOhyGQEmK0+QtWa10U/cMsCm3IqWDirp+ABfBoZOcGOkog+/dnUZAobSmrb049eAqTi+zi8CXIFCVyKh1+7s2AodN7kfB70CcMH6NTyFgGWm9TqcEBI8nvl9DYqk8/WIalkSfkQ7DOpqBbDQ2q2MiW3JWFYYwbR86T7lcuYG7sUSyd+oU44XgETVu1xhEgpgjmzAUd+LjGhWujcpflyF5QoFs9tI+Wx+ciagwyRgW6WYDpUEqbGjaNidb4R5UcF0vo3G6lFonmjwkHdF8ONgMuDm6hHG2I4Gxo4eOsn8gZWJ33u+LZcOAdo9jqA0f1EGW3G8Zmj1Ubd7YW4k3Q6HQPQhVDFAL12KEXNcIHCAc9EqDQXqS+t3ke/Hf0YLSgkhccvqgAa66U/r4vy3jajpzyTLLLovugdVpCtqMbyPVtm+JA+35yutVBmvQT/LjX3bZSaeKZkgRFBDUenqJBwRbSkA2xXUHJyoInWEIckVdd6wotB2Gumw/94cjQvMz4nyoZzgL64RuV/XWDXEj700xnvviQbIdNlnRjHZnnU1/sFWN8B2Rc2F29m8CDsHYfITfywNFe5vSVgK3ZV3P6C41/dM18uI9dTY4K40VXUglMObC5oOWfoy0PRb5GgwKZXFAmP5HNcutORHJrBetc9ss3XG4s6bFZTyRNc5KKsOcdW2sZfyc4K5WoxkhhM=
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook
      namespace: monitoring
status: {}

