apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: alertmanager-discord
spec:
    endpoints:
        - port: debug
    namespaceSelector: {}
    selector:
        matchLabels:
            monitoring: alertmanager-discord
