apiVersion: v1
kind: Service
metadata:
    name: alertmanager-discord
    labels:
        monitoring: alertmanager-discord
spec:
    clusterIP: None
    ports:
        - name: webhook
          port: 8080
          targetPort: 8080
        - name: debug
          port: 8081
          targetPort: 8081
