namespace: jsso2
commonLabels:
    app: jsso2
resources:
    - namespace.yaml
    - registry-credentials.yaml
    - sealed-secret.yaml
    - deployment.yaml
    - service.yaml
    - podmonitor.yaml
configMapGenerator:
    - name: envoy-config
      files:
          - envoy.yaml
images:
    - name: envoy
      newName: envoyproxy/envoy
      newTag: v1.16.0
    - name: backend
      newName: registry.digitalocean.com/jrockus/jsso2-backend
      newTag: 0.0.8
    - name: frontend
      newName: registry.digitalocean.com/jrockus/jsso2-frontend
      newTag: 0.0.8
