apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  creationTimestamp: null
  name: ca-root-certificate
spec:
  duration: 87600h0m0s
  isCA: true
  issuerRef:
    kind: Issuer
    name: selfsigning-issuer
  privateKey:
    algorithm: ECDSA
    size: 521
  renewBefore: 720h0m0s
  secretName: ca-root-certificate-secret
  subject:
    organizations:
    - jrock.us
  uris:
  - spiffe://jrock.us/
status: {}
