apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pgadmin
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 1Gi
    storageClassName: do-block-storage-safe
