namespace: kube-system
bases:
    - github.com/jrockway/nodedns/deploy
resources:
    - token.yaml
patches:
    - deployment.yaml
images:
    - name: nodedns
      newName: registry.digitalocean.com/jrockus/nodedns
      newTag: 0.0.19
