apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: kube-system
spec:
  encryptedData:
    .dockerconfigjson: AgCU9o6NdnDolCjMZDuqE0BS99vjdsdneyv/Tpjaqv2VyrXzCSQrOLcCFSGLaqFQF1B6WYiyjR1udovTQUmsQGmcrPlTBydzacopHrHtsQqMwCISCPEF51hYZ9CSFgcnJUGJNQv4O3NI7LqbIFg+cc92nqWpnk2g1Dm/Wkk2DTjJEKY2ojgieJd8swJYm5HGE8ZfdghXlHUlpfy2FXPirSVXToI5qkqV4SiGXeN3LzxrIeaf8VM/S4k9aPs1szUTnc9/KL0PXkJnrZLyAnFCpW9vet/h6qKqohEHKM0fkeVUZzuVcLZsr2z9aDY3koJ3eb9bu/371pSLe2XaboPKT3e6zuBReBHJYb+/sVgtejjhkDwk+m3nvpKXqkFvuQMElWeYDhH0SdIYZ9d9R3n6IyuSvZSx9W+xzmDjmG437gdHHk37AxPKyuLsn2rp1OeVaDDxuZDiVUBNRroomLh8NJmback9x4yu0LYdhQiifght/Bi1uX9IH6ezlqodfG5hH33wuiX3L6KQiUPYR/PnHc0o7S9U+O0XNOpB6JP2Z3W2Rqr+1N+1qUI0jND1doCdB2GjINLGA51qC6OVcs1Pan2OAwSzHGAf9PnSehOCCBYzLgSpBf8ylpt16hQgQRIwYkx4s6YS3eS5u/gK1ZVeSmpq6W9qbetwu4afEfvSo+v1ibfogR7HUfSVAizprydHCTHw1YmqlypJg9ZE+4dzkdl+lzTr8hyr/HWdi6ME9wh14om4YbvsxxLT6XcZNq9QqZYgNj5VjSABPFV8rONN20M4hvgxSqPxn3qxqT3ElXqoenV/j2BDGSLT9r9dAtEJ3p2H3iSrVkBfnbjjaPLLSw1s5l1UvjUVRFz95+L+AlgS+/cPrmIHeEHtK+VbW5s/iCWCXj/QKHH8c0KXKjNqQRrAweP98033f4F2DHfniNIJFvRTYmNVZhfqtnZYu1NswCVkHDoR8llYtZgpUl3iqb4iZ2DXgfAADWlg6bbWF/6/gxlLmY9nJTJWdDLZ54h4lSKO1mznDU1B5VxDAg5qOQ==
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: kube-system
    type: kubernetes.io/dockerconfigjson
status: {}

