apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: cilium
    namespace: kube-system
spec:
    selector:
        matchLabels:
            k8s-app: cilium
    podMetricsEndpoints:
        - targetPort: 9090
          path: /metrics
