apiVersion: apps/v1
kind: Deployment
metadata:
    name: envoy
    annotations:
        "sidecar.jaegertracing.io/inject": "jaeger"
spec:
    replicas: 3
    template:
        spec:
            containers:
                - name: envoy
                  image: envoy
                  command:
                      - "envoy"
                  args:
                      - "-c"
                      - "/etc/envoy/envoy.yaml"
                  volumeMounts:
                      - name: envoy-config
                        mountPath: /etc/envoy
                      - name: jrock-us-certs
                        mountPath: /jrock.us
                  readinessProbe:
                      httpGet:
                          path: /server_info
                          port: 9901
                  livenessProbe:
                      httpGet:
                          path: /server_info
                          port: 9901
                  ports:
                      - name: admin
                        containerPort: 9901
                      - name: http
                        containerPort: 80
                      - name: https
                        containerPort: 443
                      - name: http-noproxy
                        containerPort: 81
                      - name: https-noproxy
                        containerPort: 444
                  resources:
                      requests:
                          memory: "64Mi"
                      limits:
                          memory: "64Mi"
            volumes:
                - name: envoy-config
                  configMap:
                      name: envoy-config
                - name: jrock-us-certs
                  secret:
                      secretName: jrock-us-tls
            imagePullSecrets:
                - name: registry-credentials
