namespace: ingress
commonLabels:
    app: public-ingress
resources:
    - namespace.yaml
    - service.yaml
    - service-noproxy.yaml
    - deployment.yaml
    - jrock.us-cert.yaml
    - podmonitor.yaml
configMapGenerator:
    - name: envoy-config
      files: ["envoy.yaml"]
secretGenerator:
    - name: registry-credentials
      files:
          - ".dockerconfigjson=docker.secret.json"
      type: kubernetes.io/dockerconfigjson
images:
    - name: envoy
      newName: registry.jrock.us/envoy
      newTag: 18a7a733df03def4eb3937b6cab780fb561b3584
