namespace: ingress
commonLabels:
    app: public-ingress
resources:
    - namespace.yaml
    - service.yaml
    - service-noproxy.yaml
    - deployment.yaml
    - jrock.us-cert.yaml
    - podmonitor.yaml
configMapGenerator:
    - name: envoy-config
      files: ["envoy.yaml"]
secretGenerator:
    - name: registry-credentials
      files:
          - ".dockerconfigjson=docker.secret.json"
      type: kubernetes.io/dockerconfigjson
images:
    - name: envoy
      newName: docker.pkg.github.com/jrockway/jrock.us/envoy
      newTag: c8e0c71ec7b7e334e3bb02f98ac82ff72b4784b2
