apiVersion: apps/v1
kind: Deployment
metadata:
    name: ekglue
spec:
    replicas: 1
    template:
        spec:
            containers:
                - name: ekglue
                  env:
                      - name: EKGLUE_CONFIG_FILE
                        value: "/ekglue-config/ekglue.yaml"
                      - name: GRPC_GO_LOG_SEVERITY_LEVEL
                        value: info
                  volumeMounts:
                      - name: ekglue-config
                        mountPath: /ekglue-config
            volumes:
                - name: ekglue-config
                  configMap:
                      name: ekglue-config
            imagePullSecrets:
                - name: jrockus
