namespace: discovery
bases:
    - github.com/jrockway/ekglue/deploy/base
resources:
    - podmonitor.yaml
    - registry_credentials.yaml
patches:
    - deployment.yaml
configMapGenerator:
    - name: ekglue-config
      files: ["ekglue.yaml"]
images:
    - name: ekglue
      newName: registry.jrock.us/ekglue
      newTag: 0.0.60
