version: 0.1
log:
    accesslog:
        disabled: false
    level: info
    formatter: json
storage:
    filesystem:
        rootdirectory: /var/lib/registry
        maxthreads: 100
    delete:
        enabled: false
    redirect:
        disable: false
    maintenance:
        uploadpurging:
            enabled: true
            age: 168h
            interval: 24h
            dryrun: false
        readonly:
            enabled: false
auth:
    htpasswd:
        realm: registry.jrock.us
        path: /auth/htpasswd
http:
    addr: 0.0.0.0:80
    relativeurls: false
    draintimeout: 5s
    debug:
        addr: 0.0.0.0:5001
        prometheus:
            enabled: true
            path: /metrics
    headers:
        X-Content-Type-Options: [nosniff]
    http2:
        disabled: false
health:
    storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
validation:
    manifests:
        urls:
            allow:
                - ^https://registry.jrock.us/
