apiVersion: apps/v1
kind: Deployment
metadata:
    name: registry
spec:
    replicas: 1
    template:
        spec:
            containers:
                - name: registry
                  image: docker-registry
                  volumeMounts:
                      - name: config
                        mountPath: /etc/docker/registry
                      - name: auth
                        mountPath: /auth
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 80
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 80
                  ports:
                      - name: http2
                        containerPort: 80
                      - name: debug
                        containerPort: 5001
                  resources:
                      requests:
                          cpu: 500m
                          memory: "256Mi"
            volumes:
                - name: config
                  secret:
                      secretName: registry-config
                - name: auth
                  secret:
                      secretName: registry-htaccess
