namespace: docker-registry
commonLabels:
    app: docker-registry
resources:
    - namespace.yaml
    - deployment.yaml
    - service.yaml
    - podmonitor.yaml
secretGenerator:
    - name: registry-htaccess
      files:
          - "htpasswd=htpasswd.secret.txt"
    - name: registry-config
      files:
          - "config.yml=config.secret.yml"
images:
    #    - name: docker-registry
    #      newName: docker.io/registry
    #      newTag: 2.7.1
    - name: docker-registry
      newName: jrockway/registry
      newTag: 6b972e50feee79bbe1de9d18668e9e4e5e729355
