namespace: docker-registry
commonLabels:
    app: docker-registry
resources:
    - namespace.yaml
    - deployment.yaml
    - service.yaml
secretGenerator:
    - name: registry-htaccess
      files:
          - "htpasswd=htpasswd.secret.txt"
    - name: registry-config
      files:
          - "config.yml=config.secret.yml"
images:
    - name: docker-registry
      newName: docker.io/registry
      newTag: 2.7.1
