apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: registry
spec:
    selector:
        matchLabels:
            app: docker-registry
    podMetricsEndpoints:
        - port: debug
          path: /metrics
