apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: registry-volume
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 8Gi
    storageClassName: do-block-storage
