namespace: ingress
commonLabels:
    app: noproxy-public-ingress
resources:
    - service.yaml
    - deployment.yaml
    - podmonitor.yaml
    - poddisruptionbudget.yaml
configMapGenerator:
    - name: noproxy-envoy-config
      files: ["envoy.yaml"]
images:
    - name: envoy
      newName: envoyproxy/envoy
      newTag: v1.14.1
