apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: noproxy-envoy
spec:
    selector:
        matchLabels:
            app: noproxy-public-ingress
    podMetricsEndpoints:
        - port: envoy-admin
          path: /stats/prometheus
