resources:
    - name: jrock-us-git
      type: git
      icon: github-circle
      webhook_token: ((webhook.token))
      source:
          uri: https://github.com/jrockway/jrock.us

    - name: www-version
      type: semver
      icon: counter
      source:
          driver: s3
          bucket: ((versions.bucket))
          access_key_id: ((versions.access_key_id))
          secret_access_key: ((versions.secret_access_key))
          region_name: ((versions.region_name))
          endpoint: ((versions.endpoint))
          key: www-version
          initial_version: 0.0.1

    - name: www-image
      type: registry-image
      icon: docker
      source:
          repository: registry.jrock.us/www
          username: ((registry.username))
          password: ((registry.password))

jobs:
    - name: www
      public: true
      plan:
          - get: jrock-us-git
            trigger: true
          - get: www-version
            params:
                bump: patch
          - task: build
            privileged: true
            file: jrock-us-git/ci/build-container.yaml
            vars:
                code: jrock-us-git
                context: www
          - put: www-image
            params:
                image: image/image.tar
          - task: check-config
            image: www-image
            config:
                platform: linux
                run:
                    path: /usr/sbin/nginx
                    args: ["-t"]
          - put: www-image
            params:
                image: image/image.tar
                additional_tags: www-version/version
          - put: www-version
            params:
                file: www-version/version
