apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: envoy
spec:
    secretName: envoy-client-tls
    issuerRef:
        name: ca-issuer
        kind: ClusterIssuer
    dnsNames:
        - public
        - public.ingress
        - public.ingress.svc
        - public.ingress.svc.cluster.local
