apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  creationTimestamp: null
  name: envoy
spec:
  dnsNames:
  - public
  - public.ingress
  - public.ingress.svc
  - public.ingress.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
  secretName: envoy-client-tls
status: {}
