namespace: ingress
commonLabels:
    app: public-ingress
resources:
    - registry-credentials-sealedsecret.yaml
    - service.yaml
    - deployment.yaml
    - podmonitor.yaml
    - poddisruptionbudget.yaml
    - client-cert.yaml
    - config-test-job.yaml
patchesJson6902:
    - target:
          group: batch
          version: v1
          kind: Job
          name: envoy-config-test
      path: remove-app-label.yaml
configMapGenerator:
    - name: envoy-config
      files: ["envoy.yaml", "sds.yaml", "client-sds.yaml", "client-validation-sds.yaml"]
images:
    - name: envoy
      newName: envoyproxy/envoy-distroless
      newTag: v1.26.1
    - name: jsso2
      newName: registry.digitalocean.com/jrockus/jsso2-backend
      newTag: 0.0.8
