namespace: ingress
commonLabels:
    app: public-ingress
resources:
    - service.yaml
    - deployment.yaml
    - podmonitor.yaml
    - poddisruptionbudget.yaml
    - client-cert.yaml
configMapGenerator:
    - name: envoy-config
      files: ["envoy.yaml", "sds.yaml", "client-sds.yaml", "client-validation-sds.yaml"]
    - name: envoy-policy
      files: ["policy.rego=access/policy.rego"]
secretGenerator:
    - name: registry-credentials
      files:
          - ".dockerconfigjson=docker.secret.json"
      type: kubernetes.io/dockerconfigjson
images:
    - name: envoy
      newName: envoyproxy/envoy
      newTag: v1.14.1
    - name: jsso
      newName: registry.jrock.us/jsso-envoy-plugin
      digest: sha256:d7443754b3c5a36d5f3615f5eb574d8309ac2d501d861ce08a5c592d73b2dd3b
