namespace: ingress
commonLabels:
    app: public-ingress
resources:
    - service.yaml
    - deployment.yaml
    - podmonitor.yaml
configMapGenerator:
    - name: envoy-config
      files: ["envoy.yaml"]
    - name: envoy-policy
      files: ["policy.rego=access/policy.rego"]
secretGenerator:
    - name: registry-credentials
      files:
          - ".dockerconfigjson=docker.secret.json"
      type: kubernetes.io/dockerconfigjson
images:
    - name: envoy
      newName: registry.jrock.us/envoy
      newTag: 18a7a733df03def4eb3937b6cab780fb561b3584
    - name: jsso
      newName: registry.jrock.us/jsso-envoy-plugin
      digest: sha256:6b0282898cc31f84b239ad1db5555ee11088a8f60f53d7cbf7299137c89b0eb2
