apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: envoy
spec:
    selector:
        matchLabels:
            app: public-ingress
    podMetricsEndpoints:
        - port: envoy-admin
          path: /stats/prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: envoy-jsso
spec:
    selector:
        matchLabels:
            app: public-ingress
    podMetricsEndpoints:
        - port: jsso-admin
          path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: envoy-jsso2
spec:
    selector:
        matchLabels:
            app: public-ingress
    podMetricsEndpoints:
        - port: jsso2-admin
          path: /metrics
