apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
    name: jaeger
spec:
    strategy: allinone
    allInOne:
        options:
            log-level: info
    ui:
        options:
            dependencies:
                menuEnabled: true
    storage:
        type: badger
        options:
            badger:
                ephemeral: false
                directory-key: /badger/key
                directory-value: /badger/data
    ingress:
        enabled: false
    resources:
        requests:
            cpu: 100m
            memory: 256Mi
        limits:
            memory: 256Mi
    volumes:
        - name: badger
          persistentVolumeClaim:
              claimName: badger
    volumeMounts:
        - name: badger
          mountPath: /badger
