apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
    name: jaeger
spec:
    strategy: allinone
    allInOne:
        options:
            log-level: info
    ui:
        options:
            dependencies:
                menuEnabled: true
    storage:
        type: memory
        options:
            memory.max-traces: "1000000"
    ingress:
        enabled: false
    resources:
        requests:
            cpu: 100m
            memory: 200Mi
        limits:
            memory: 1200Mi
