apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
    name: jaeger
spec:
    strategy: allinone
    allInOne:
        options:
            log-level: info
        resources:
            requests:
                cpu: 100m
                memory: 2Gi
            limits:
                memory: 2Gi
    ui:
        options:
            dependencies:
                menuEnabled: true
    storage:
        type: memory
        options:
            memory.max-traces: 130000 # ~15k per trace based on data
    ingress:
        enabled: false
    agent:
        resources:
            requests:
                cpu: 1m
                memory: 30Mi
            limits:
                memory: 30Mi
