apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
    name: jaeger
spec:
    strategy: allinone
    allInOne:
        options:
            log-level: info
    ui:
        options:
            dependencies:
                menuEnabled: true
    storage:
        options:
            memory:
                max-traces: 1000001 # one more than the default to please argo?
    resources:
        requests:
            cpu: 100m
            memory: 200Mi
        limits:
            memory: 1200Mi
