apiVersion: apps/v1
kind: Deployment
metadata:
    name: jaeger-operator
spec:
    template:
        spec:
            containers:
                - name: jaeger-operator
                  resources:
                      requests:
                          cpu: 10m
                          memory: 50Mi
                      limits:
                          memory: 50Mi
