apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: jaeger
spec:
    podMetricsEndpoints:
        - port: admin-http
          path: /metrics
    selector:
        matchLabels:
            app: jaeger
