apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: badger
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 20Gi
    storageClassName: do-block-storage-safe
