apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: jaeger-badger
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 5Gi
    storageClassName: do-block-storage-safe
