namespace: concourse
resources:
    # - worker-service-account.yaml
    # - worker-role.yaml
    # - worker-rolebinding.yaml
    # - worker-service.yaml
    # - worker-disruption-budget.yaml
    # - worker-statefulset.yaml
    # - worker-sealedsecret.yaml
    - web-service-account.yaml
    - web-role.yaml
    - web-service.yaml
    - web-deployment.yaml
    - web-servicemonitor.yaml
    - web-sealedsecret.yaml
configMapGenerator:
    - name: concourse-worker
      files:
          - "pre-stop-hook.sh"
images:
    - name: concourse
      newName: concourse/concourse
      newTag: "6.4.0"
