---
apiVersion: v1
kind: Namespace
metadata:
    name: concourse-main
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
    name: concourse-web-main
    namespace: concourse-main
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: concourse-web
subjects:
    - kind: ServiceAccount
      name: concourse-web
      namespace: concourse
