apiVersion: apps/v1
kind: Deployment
metadata:
    name: concourse-web
    labels:
        app: concourse-web
spec:
    replicas: 2
    selector:
        matchLabels:
            app: concourse-web
    template:
        metadata:
            labels:
                app: concourse-web
        spec:
            serviceAccountName: concourse-web
            containers:
                - name: concourse-web
                  image: concourse
                  imagePullPolicy: "IfNotPresent"
                  args:
                      - web
                  env:
                      - name: CONCOURSE_CLUSTER_NAME
                        value: "ci.jrock.us"
                      - name: CONCOURSE_ENABLE_GLOBAL_RESOURCES
                        value: "true"
                      - name: CONCOURSE_ENABLE_REDACT_SECRETS
                        value: "true"
                      - name: CONCOURSE_SECRET_RETRY_ATTEMPTS
                        value: "5"
                      - name: CONCOURSE_SECRET_RETRY_INTERVAL
                        value: "1s"
                      - name: CONCOURSE_CAPTURE_ERROR_METRICS
                        value: "true"
                      - name: CONCOURSE_LOG_LEVEL
                        value: "info"
                      - name: CONCOURSE_BIND_PORT
                        value: "8080"
                      - name: CONCOURSE_BIND_IP
                        value: "0.0.0.0"
                      - name: CONCOURSE_ADD_LOCAL_USER
                        valueFrom:
                            secretKeyRef:
                                name: concourse-web
                                key: local-users
                      - name: CONCOURSE_EXTERNAL_URL
                        value: "https://ci.jrock.us"
                      - name: CONCOURSE_DEBUG_BIND_IP
                        value: "0.0.0.0"
                      - name: CONCOURSE_DEBUG_BIND_PORT
                        value: "8079"
                      - name: CONCOURSE_INTERCEPT_IDLE_TIMEOUT
                        value: "0m"
                      - name: CONCOURSE_GLOBAL_RESOURCE_CHECK_TIMEOUT
                        value: "1h"
                      - name: CONCOURSE_RESOURCE_CHECKING_INTERVAL
                        value: "1m"
                      - name: CONCOURSE_RESOURCE_TYPE_CHECKING_INTERVAL
                        value: "1m"
                      - name: CONCOURSE_CONTAINER_PLACEMENT_STRATEGY
                        value: "volume-locality"
                      - name: CONCOURSE_BAGGAGECLAIM_RESPONSE_HEADER_TIMEOUT
                        value: "1m"
                      - name: CONCOURSE_BUILD_TRACKER_INTERVAL
                        value: "10s"
                      - name: CONCOURSE_POSTGRES_HOST
                        value: "master.postgres.svc.cluster.local"
                      - name: CONCOURSE_POSTGRES_PORT
                        value: "5432"
                      - name: CONCOURSE_POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                name: concourse-web
                                key: postgresql-user
                      - name: CONCOURSE_POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: concourse-web
                                key: postgresql-password
                      - name: CONCOURSE_POSTGRES_SSLMODE
                        value: "disable"
                      - name: CONCOURSE_POSTGRES_CONNECT_TIMEOUT
                        value: "10s"
                      - name: CONCOURSE_POSTGRES_DATABASE
                        value: "atc"
                      - name: CONCOURSE_KUBERNETES_IN_CLUSTER
                        value: "true"
                      - name: CONCOURSE_KUBERNETES_NAMESPACE_PREFIX
                        value: concourse-
                      - name: CONCOURSE_PROMETHEUS_BIND_IP
                        value: "0.0.0.0"
                      - name: CONCOURSE_PROMETHEUS_BIND_PORT
                        value: "9391"
                      - name: CONCOURSE_X_FRAME_OPTIONS
                        value: "deny"
                      - name: CONCOURSE_GC_INTERVAL
                        value: "30s"
                      - name: CONCOURSE_GC_ONE_OFF_GRACE_PERIOD
                        value: "5m"
                      - name: CONCOURSE_GC_MISSING_GRACE_PERIOD
                        value: "5m"
                      - name: CONCOURSE_COOKIE_SECURE
                        value: "true"
                      - name: CONCOURSE_AUTH_DURATION
                        value: "240h"
                      - name: CONCOURSE_SESSION_SIGNING_KEY
                        value: "/concourse-keys/session_signing_key"
                      - name: CONCOURSE_MAIN_TEAM_LOCAL_USER
                        value: "jrockway"
                      - name: POD_IP
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: CONCOURSE_PEER_ADDRESS
                        value: "$(POD_IP)"
                      - name: CONCOURSE_TSA_LOG_LEVEL
                        value: "info"
                      - name: CONCOURSE_TSA_BIND_IP
                        value: "0.0.0.0"
                      - name: CONCOURSE_TSA_BIND_PORT
                        value: "2222"
                      - name: CONCOURSE_TSA_DEBUG_BIND_IP
                        value: "0.0.0.0"
                      - name: CONCOURSE_TSA_DEBUG_BIND_PORT
                        value: "2221"
                      - name: CONCOURSE_TSA_HOST_KEY
                        value: "/concourse-keys/host_key"
                      - name: CONCOURSE_TSA_AUTHORIZED_KEYS
                        value: "/concourse-keys/worker_key.pub"
                      - name: CONCOURSE_TSA_HEARTBEAT_INTERVAL
                        value: "30s"
                      - name: CONCOURSE_DEFAULT_TASK_CPU_LIMIT
                        value: "1024" # docker "cpu shares"
                      - name: CONCOURSE_DEFAULT_TASK_MEMORY_LIMIT
                        value: "1024000000"
                  ports:
                      - name: atc
                        containerPort: 8080
                      - name: tsa
                        containerPort: 2222
                      - name: atc-debug
                        containerPort: 8079
                      - name: prometheus
                        containerPort: 9391
                  livenessProbe:
                      failureThreshold: 5
                      httpGet:
                          path: /api/v1/info
                          port: atc
                      initialDelaySeconds: 10
                      periodSeconds: 15
                      timeoutSeconds: 3
                  readinessProbe:
                      httpGet:
                          path: /api/v1/info
                          port: atc
                  resources:
                      limits:
                          memory: 128Mi
                      requests:
                          cpu: 300m
                          memory: 128Mi
                  volumeMounts:
                      - name: concourse-keys
                        mountPath: "/concourse-keys"
                        readOnly: true
            volumes:
                - name: concourse-keys
                  secret:
                      secretName: concourse-web
                      defaultMode: 0400
