apiVersion: v1
kind: Service
metadata:
    name: concourse-web-tsa
    labels:
        app: concourse-web
spec:
    type: NodePort
    ports:
        - name: tsa
          port: 2222
          targetPort: tsa
    selector:
        app: concourse-web
