apiVersion: v1
kind: Service
metadata:
    name: concourse-web
    labels:
        app: concourse-web
spec:
    type: ClusterIP
    clusterIP: None
    ports:
        - name: atc
          port: 8080
          targetPort: atc
        - name: tsa
          port: 2222
          targetPort: tsa
        - name: prometheus
          port: 9391
          targetPort: prometheus
    selector:
        app: concourse-web
