apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
    name: concourse-worker
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: concourse-worker
subjects:
    - kind: ServiceAccount
      name: concourse-worker
