apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: concourse-worker
    labels:
        app: concourse-worker
spec:
    replicas: 1
    serviceName: concourse-worker
    selector:
        matchLabels:
            app: concourse-worker
    template:
        metadata:
            labels:
                app: concourse-worker
        spec:
            serviceAccountName: concourse-worker
            terminationGracePeriodSeconds: 60
            initContainers:
                - name: concourse-worker-init-rm
                  image: concourse
                  imagePullPolicy: "IfNotPresent"
                  securityContext:
                      privileged: true
                  command:
                      - /bin/bash
                  args:
                      - -ce
                      - |-
                          for v in $((btrfs subvolume list --sort=-ogen "/concourse-work-dir" || true) | awk '{print $9}'); do
                            (btrfs subvolume show "/concourse-work-dir/$v" && btrfs subvolume delete "/concourse-work-dir/$v") || true
                          done
                          rm -rf "/concourse-work-dir/*"
                  volumeMounts:
                      - name: concourse-work-dir
                        mountPath: "/concourse-work-dir"
            containers:
                - name: concourse-worker
                  image: concourse
                  imagePullPolicy: "IfNotPresent"
                  args:
                      - worker
                  livenessProbe:
                      failureThreshold: 5
                      httpGet:
                          path: /
                          port: worker-hc
                      initialDelaySeconds: 10
                      periodSeconds: 15
                      timeoutSeconds: 3
                  lifecycle:
                      preStop:
                          exec:
                              command:
                                  - "/bin/bash"
                                  - "/pre-stop-hook.sh"
                  env:
                      - name: CONCOURSE_SWEEP_INTERVAL
                        value: "30s"
                      - name: CONCOURSE_CONNECTION_DRAIN_TIMEOUT
                        value: "30s"
                      - name: CONCOURSE_HEALTHCHECK_BIND_IP
                        value: "0.0.0.0"
                      - name: CONCOURSE_HEALTHCHECK_BIND_PORT
                        value: "8888"
                      - name: CONCOURSE_HEALTHCHECK_TIMEOUT
                        value: "5s"
                      - name: CONCOURSE_DEBUG_BIND_IP
                        value: "127.0.0.1"
                      - name: CONCOURSE_DEBUG_BIND_PORT
                        value: "7776"
                      - name: CONCOURSE_WORK_DIR
                        value: "/concourse-work-dir"
                      - name: CONCOURSE_BIND_IP
                        value: "127.0.0.1"
                      - name: CONCOURSE_BIND_PORT
                        value: "7777"
                      - name: CONCOURSE_LOG_LEVEL
                        value: "info"
                      - name: CONCOURSE_TSA_HOST
                        value: "concourse-web:2222"
                      - name: CONCOURSE_TSA_PUBLIC_KEY
                        value: "/concourse-keys/host_key.pub"
                      - name: CONCOURSE_TSA_WORKER_PRIVATE_KEY
                        value: "/concourse-keys/worker_key"
                      - name: CONCOURSE_GARDEN_BIN
                        value: "gdn"
                      - name: CONCOURSE_BAGGAGECLAIM_LOG_LEVEL
                        value: "info"
                      - name: CONCOURSE_BAGGAGECLAIM_BIND_IP
                        value: "127.0.0.1"
                      - name: CONCOURSE_BAGGAGECLAIM_BIND_PORT
                        value: "7788"
                      - name: CONCOURSE_BAGGAGECLAIM_DEBUG_BIND_IP
                        value: "127.0.0.1"
                      - name: CONCOURSE_BAGGAGECLAIM_DEBUG_BIND_PORT
                        value: "7787"
                      - name: CONCOURSE_BAGGAGECLAIM_DRIVER
                        value: "naive"
                      - name: CONCOURSE_BAGGAGECLAIM_BTRFS_BIN
                        value: "btrfs"
                      - name: CONCOURSE_BAGGAGECLAIM_MKFS_BIN
                        value: "mkfs.btrfs"
                      - name: CONCOURSE_VOLUME_SWEEPER_MAX_IN_FLIGHT
                        value: "5"
                      - name: CONCOURSE_CONTAINER_SWEEPER_MAX_IN_FLIGHT
                        value: "5"
                      - name: CONCOURSE_TRACING_JAEGER_ENDPOINT
                        value: http://jaeger-collector.observability.svc.cluster.local:14268/api/traces
                  ports:
                      - name: worker-hc
                        containerPort: 8888
                  resources:
                      requests:
                          cpu: 1000m
                          memory: 600Mi
                      limits:
                          cpu: 3000m
                          memory: 3200Mi
                  securityContext:
                      privileged: true
                  volumeMounts:
                      - name: concourse-keys
                        mountPath: "/concourse-keys"
                        readOnly: true
                      - name: concourse-work-dir
                        mountPath: "/concourse-work-dir"
                      - name: pre-stop-hook
                        mountPath: /pre-stop-hook.sh
                        subPath: pre-stop-hook.sh
            affinity:
                podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                        - weight: 100
                          podAffinityTerm:
                              topologyKey: kubernetes.io/hostname
                              labelSelector:
                                  matchLabels:
                                      app: concourse-worker
            volumes:
                - name: pre-stop-hook
                  configMap:
                      name: concourse-worker
                - name: concourse-keys
                  secret:
                      secretName: concourse-worker
                      defaultMode: 0400
                      items:
                          - key: host-key-pub
                            path: host_key.pub
                          - key: worker-key
                            path: worker_key
    volumeClaimTemplates:
        - metadata:
              name: concourse-work-dir
          spec:
              accessModes:
                  - ReadWriteOnce
              volumeMode: Filesystem
              resources:
                  requests:
                      storage: 40Gi
              storageClassName: do-block-storage
    updateStrategy:
        type: RollingUpdate
    podManagementPolicy: Parallel
