apiVersion: v1
kind: Service
metadata:
    name: concourse-worker
    labels:
        app: concourse-worker
spec:
    type: ClusterIP
    clusterIP: None
    ports: []
    selector:
        app: concourse-worker
