apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  creationTimestamp: null
  name: letsencrypt-issuer
spec:
  acme:
    email: jon@jrock.us
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            key: token
            name: digitalocean-dns-token
status: {}
