apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
    name: letsencrypt-staging-issuer
spec:
    acme:
        email: jon@jrock.us
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: letsencrypt-staging-issuer-account-key
        solvers:
            - dns01:
                  digitalocean:
                      tokenSecretRef:
                          name: digitalocean-dns-token
                          key: token
