# helm install -f values.yaml stable/prometheus-node-exporter
namespaceOverride: monitoring
prometheus:
    monitor:
        enabled: true
resources:
    limits:
        memory: 50Mi
    requests:
        cpu: 100m
        memory: 50Mi
