name: Build Envoy
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Build
              run: docker build third_party/envoy --file third_party/envoy/Dockerfile --tag docker.pkg.github.com/jrockway/jrock.us/envoy:${{ github.sha }}
            - name: Push
              run: |
                  docker login docker.pkg.github.com -u jrockway -p ${{ secrets.GITHUB_TOKEN }} && \
                  docker push docker.pkg.github.com/jrockway/jrock.us/envoy:${{ github.sha }}
