name: Build www.jrock.us container
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Build
              run: docker build www --file www/Dockerfile --tag registry.jrock.us/www:${{ github.sha }}
            - name: Push
              run: |
                  docker login registry.jrock.us -u jrockway -p '${{ secrets.registry }}' && \
                  docker push registry.jrock.us/www:${{ github.sha }}
